typedef ArticleViewHistoryRecord = ({String date, int views});

class WikiLanguage {
  final String code;
  final String name;

  const WikiLanguage({required this.code, required this.name});

  @override
  String toString() {
    return "$name ($code)";
  }

  static const defaultLanguageCode = WikiLanguage(code: "en", name: "English");

  static const List<WikiLanguage> languages = [
    WikiLanguage(code: "ab", name: "Abkhazian"),
    WikiLanguage(code: "ace", name: "Acehnese"),
    WikiLanguage(code: "ady", name: "Adyghe"),
    WikiLanguage(code: "aa", name: "Afar"),
    WikiLanguage(code: "af", name: "Afrikaans"),
    WikiLanguage(code: "ak", name: "Akan"),
    WikiLanguage(code: "sq", name: "Albanian"),
    WikiLanguage(code: "als", name: "Alemannic"),
    WikiLanguage(code: "alt", name: "Altai"),
    WikiLanguage(code: "am", name: "Amharic"),
    WikiLanguage(code: "ami", name: "Amis"),
    WikiLanguage(code: "anp", name: "Angika"),
    WikiLanguage(code: "ang", name: "Anglo-Saxon"),
    WikiLanguage(code: "ar", name: "Arabic"),
    WikiLanguage(code: "an", name: "Aragonese"),
    WikiLanguage(code: "arc", name: "Aramaic"),
    WikiLanguage(code: "hy", name: "Armenian"),
    WikiLanguage(code: "roa-rup", name: "Aromanian"),
    WikiLanguage(code: "as", name: "Assamese"),
    WikiLanguage(code: "ast", name: "Asturian"),
    WikiLanguage(code: "tay", name: "Atayal"),
    WikiLanguage(code: "atj", name: "Atikamekw"),
    WikiLanguage(code: "av", name: "Avar"),
    WikiLanguage(code: "awa", name: "Awadhi"),
    WikiLanguage(code: "ay", name: "Aymara"),
    WikiLanguage(code: "az", name: "Azerbaijani"),
    WikiLanguage(code: "ban", name: "Balinese"),
    WikiLanguage(code: "bm", name: "Bambara"),
    WikiLanguage(code: "bjn", name: "Banjar"),
    WikiLanguage(code: "map-bms", name: "Banyumasan"),
    WikiLanguage(code: "ba", name: "Bashkir"),
    WikiLanguage(code: "eu", name: "Basque"),
    WikiLanguage(code: "bar", name: "Bavarian"),
    WikiLanguage(code: "be", name: "Belarusian"),
    WikiLanguage(code: "be-tarask", name: "Belarusian (Taraškievica)"),
    WikiLanguage(code: "bn", name: "Bengali"),
    WikiLanguage(code: "bh", name: "Bihari"),
    WikiLanguage(code: "bpy", name: "Bishnupriya Manipuri"),
    WikiLanguage(code: "bi", name: "Bislama"),
    WikiLanguage(code: "bs", name: "Bosnian"),
    WikiLanguage(code: "br", name: "Breton"),
    WikiLanguage(code: "bug", name: "Buginese"),
    WikiLanguage(code: "bg", name: "Bulgarian"),
    WikiLanguage(code: "my", name: "Burmese"),
    WikiLanguage(code: "bxr", name: "Buryat (Russia)"),
    WikiLanguage(code: "zh-yue", name: "Cantonese"),
    WikiLanguage(code: "ca", name: "Catalan"),
    WikiLanguage(code: "ceb", name: "Cebuano"),
    WikiLanguage(code: "bcl", name: "Central Bicolano"),
    WikiLanguage(code: "ch", name: "Chamorro"),
    WikiLanguage(code: "ce", name: "Chechen"),
    WikiLanguage(code: "chr", name: "Cherokee"),
    WikiLanguage(code: "chy", name: "Cheyenne"),
    WikiLanguage(code: "ny", name: "Chichewa"),
    WikiLanguage(code: "zh", name: "Chinese"),
    WikiLanguage(code: "cho", name: "Choctaw"),
    WikiLanguage(code: "cv", name: "Chuvash"),
    WikiLanguage(code: "zh-classical", name: "Classical Chinese"),
    WikiLanguage(code: "kw", name: "Cornish"),
    WikiLanguage(code: "co", name: "Corsican"),
    WikiLanguage(code: "cr", name: "Cree"),
    WikiLanguage(code: "crh", name: "Crimean Tatar"),
    WikiLanguage(code: "hr", name: "Croatian"),
    WikiLanguage(code: "cs", name: "Czech"),
    WikiLanguage(code: "dga", name: "Dagaare"),
    WikiLanguage(code: "dag", name: "Dagbani"),
    WikiLanguage(code: "da", name: "Danish"),
    WikiLanguage(code: "din", name: "Dinka"),
    WikiLanguage(code: "dv", name: "Divehi"),
    WikiLanguage(code: "dty", name: "Doteli"),
    WikiLanguage(code: "nl", name: "Dutch"),
    WikiLanguage(code: "nds-nl", name: "Dutch Low Saxon"),
    WikiLanguage(code: "dz", name: "Dzongkha"),
    WikiLanguage(code: "arz", name: "Egyptian Arabic"),
    WikiLanguage(code: "eml", name: "Emilian-Romagnol"),
    WikiLanguage(code: "en", name: "English"),
    WikiLanguage(code: "myv", name: "Erzya"),
    WikiLanguage(code: "eo", name: "Esperanto"),
    WikiLanguage(code: "et", name: "Estonian"),
    WikiLanguage(code: "ee", name: "Ewe"),
    WikiLanguage(code: "ext", name: "Extremaduran"),
    WikiLanguage(code: "fat", name: "Fante"),
    WikiLanguage(code: "fo", name: "Faroese"),
    WikiLanguage(code: "hif", name: "Fiji Hindi"),
    WikiLanguage(code: "fj", name: "Fijian"),
    WikiLanguage(code: "fi", name: "Finnish"),
    WikiLanguage(code: "fon", name: "Fon"),
    WikiLanguage(code: "frp", name: "Franco-Provençal/Arpitan"),
    WikiLanguage(code: "fr", name: "French"),
    WikiLanguage(code: "fur", name: "Friulian"),
    WikiLanguage(code: "ff", name: "Fula"),
    WikiLanguage(code: "gag", name: "Gagauz"),
    WikiLanguage(code: "gl", name: "Galician"),
    WikiLanguage(code: "gan", name: "Gan"),
    WikiLanguage(code: "ka", name: "Georgian"),
    WikiLanguage(code: "de", name: "German"),
    WikiLanguage(code: "gpe", name: "Ghanaian Pidgin"),
    WikiLanguage(code: "glk", name: "Gilaki"),
    WikiLanguage(code: "gom", name: "Goan Konkani"),
    WikiLanguage(code: "gor", name: "Gorontalo"),
    WikiLanguage(code: "got", name: "Gothic"),
    WikiLanguage(code: "el", name: "Greek"),
    WikiLanguage(code: "kl", name: "Greenlandic"),
    WikiLanguage(code: "gn", name: "Guarani"),
    WikiLanguage(code: "gcr", name: "Guianan Creole"),
    WikiLanguage(code: "gu", name: "Gujarati"),
    WikiLanguage(code: "guw", name: "Gun"),
    WikiLanguage(code: "gur", name: "Gurenɛ"),
    WikiLanguage(code: "ht", name: "Haitian"),
    WikiLanguage(code: "hak", name: "Hakka"),
    WikiLanguage(code: "ha", name: "Hausa"),
    WikiLanguage(code: "haw", name: "Hawaiian"),
    WikiLanguage(code: "he", name: "Hebrew"),
    WikiLanguage(code: "hz", name: "Herero"),
    WikiLanguage(code: "mrj", name: "Hill Mari"),
    WikiLanguage(code: "hi", name: "Hindi"),
    WikiLanguage(code: "ho", name: "Hiri Motu"),
    WikiLanguage(code: "hu", name: "Hungarian"),
    WikiLanguage(code: "is", name: "Icelandic"),
    WikiLanguage(code: "io", name: "Ido"),
    WikiLanguage(code: "ig", name: "Igbo"),
    WikiLanguage(code: "ilo", name: "Ilokano"),
    WikiLanguage(code: "smn", name: "Inari Sami"),
    WikiLanguage(code: "id", name: "Indonesian"),
    WikiLanguage(code: "inh", name: "Ingush"),
    WikiLanguage(code: "ia", name: "Interlingua"),
    WikiLanguage(code: "ie", name: "Interlingue"),
    WikiLanguage(code: "iu", name: "Inuktitut"),
    WikiLanguage(code: "ik", name: "Inupiak"),
    WikiLanguage(code: "ga", name: "Irish"),
    WikiLanguage(code: "it", name: "Italian"),
    WikiLanguage(code: "jam", name: "Jamaican"),
    WikiLanguage(code: "ja", name: "Japanese"),
    WikiLanguage(code: "jv", name: "Javanese"),
    WikiLanguage(code: "kbd", name: "Kabardian Circassian"),
    WikiLanguage(code: "kbp", name: "Kabiye"),
    WikiLanguage(code: "kab", name: "Kabyle"),
    WikiLanguage(code: "xal", name: "Kalmyk"),
    WikiLanguage(code: "kn", name: "Kannada"),
    WikiLanguage(code: "kr", name: "Kanuri"),
    WikiLanguage(code: "pam", name: "Kapampangan"),
    WikiLanguage(code: "krc", name: "Karachay-Balkar"),
    WikiLanguage(code: "kaa", name: "Karakalpak"),
    WikiLanguage(code: "ks", name: "Kashmiri"),
    WikiLanguage(code: "csb", name: "Kashubian"),
    WikiLanguage(code: "kk", name: "Kazakh"),
    WikiLanguage(code: "km", name: "Khmer"),
    WikiLanguage(code: "ki", name: "Kikuyu"),
    WikiLanguage(code: "rw", name: "Kinyarwanda"),
    WikiLanguage(code: "ky", name: "Kirghiz"),
    WikiLanguage(code: "rn", name: "Kirundi"),
    WikiLanguage(code: "kv", name: "Komi"),
    WikiLanguage(code: "koi", name: "Komi-Permyak"),
    WikiLanguage(code: "kg", name: "Kongo"),
    WikiLanguage(code: "ko", name: "Korean"),
    WikiLanguage(code: "avk", name: "Kotava"),
    WikiLanguage(code: "kj", name: "Kuanyama"),
    WikiLanguage(code: "ku", name: "Kurdish"),
    WikiLanguage(code: "lld", name: "Ladin"),
    WikiLanguage(code: "lad", name: "Ladino"),
    WikiLanguage(code: "lbe", name: "Lak"),
    WikiLanguage(code: "lo", name: "Lao"),
    WikiLanguage(code: "ltg", name: "Latgalian"),
    WikiLanguage(code: "la", name: "Latin"),
    WikiLanguage(code: "lv", name: "Latvian"),
    WikiLanguage(code: "lez", name: "Lezgian"),
    WikiLanguage(code: "lij", name: "Ligurian"),
    WikiLanguage(code: "li", name: "Limburgish"),
    WikiLanguage(code: "ln", name: "Lingala"),
    WikiLanguage(code: "lfn", name: "Lingua Franca Nova 2"),
    WikiLanguage(code: "lt", name: "Lithuanian"),
    WikiLanguage(code: "olo", name: "Livvi-Karelian"),
    WikiLanguage(code: "jbo", name: "Lojban"),
    WikiLanguage(code: "lmo", name: "Lombard"),
    WikiLanguage(code: "nds", name: "Low Saxon"),
    WikiLanguage(code: "dsb", name: "Lower Sorbian"),
    WikiLanguage(code: "lg", name: "Luganda"),
    WikiLanguage(code: "lb", name: "Luxembourgish"),
    WikiLanguage(code: "mk", name: "Macedonian"),
    WikiLanguage(code: "mad", name: "Madurese"),
    WikiLanguage(code: "mai", name: "Maithili"),
    WikiLanguage(code: "mg", name: "Malagasy"),
    WikiLanguage(code: "ms", name: "Malay"),
    WikiLanguage(code: "ml", name: "Malayalam"),
    WikiLanguage(code: "mt", name: "Maltese"),
    WikiLanguage(code: "gv", name: "Manx"),
    WikiLanguage(code: "mi", name: "Maori"),
    WikiLanguage(code: "mr", name: "Marathi"),
    WikiLanguage(code: "mh", name: "Marshallese"),
    WikiLanguage(code: "mzn", name: "Mazandarani"),
    WikiLanguage(code: "mhr", name: "Meadow Mari"),
    WikiLanguage(code: "mni", name: "Meitei"),
    WikiLanguage(code: "cdo", name: "Min Dong"),
    WikiLanguage(code: "zh-min-nan", name: "Min Nan"),
    WikiLanguage(code: "min", name: "Minangkabau"),
    WikiLanguage(code: "xmf", name: "Mingrelian"),
    WikiLanguage(code: "mwl", name: "Mirandese"),
    WikiLanguage(code: "mdf", name: "Moksha"),
    WikiLanguage(code: "mnw", name: "Mon"),
    WikiLanguage(code: "mn", name: "Mongolian"),
    WikiLanguage(code: "zgh", name: "Moroccan Amazigh"),
    WikiLanguage(code: "ary", name: "Moroccan Arabic"),
    WikiLanguage(code: "mus", name: "Muscogee"),
    WikiLanguage(code: "nqo", name: "N'Ko"),
    WikiLanguage(code: "nah", name: "Nahuatl"),
    WikiLanguage(code: "na", name: "Nauruan"),
    WikiLanguage(code: "nv", name: "Navajo"),
    WikiLanguage(code: "ng", name: "Ndonga"),
    WikiLanguage(code: "nap", name: "Neapolitan"),
    WikiLanguage(code: "ne", name: "Nepali"),
    WikiLanguage(code: "new", name: "Newar / Nepal Bhasa"),
    WikiLanguage(code: "nia", name: "Nias"),
    WikiLanguage(code: "pcm", name: "Nigerian Pidgin"),
    WikiLanguage(code: "pih", name: "Norfolk"),
    WikiLanguage(code: "nrm", name: "Norman"),
    WikiLanguage(code: "frr", name: "North Frisian"),
    WikiLanguage(code: "lrc", name: "Northern Luri"),
    WikiLanguage(code: "se", name: "Northern Sami"),
    WikiLanguage(code: "nso", name: "Northern Sotho"),
    WikiLanguage(code: "no", name: "Norwegian (Bokmål)"),
    WikiLanguage(code: "nn", name: "Norwegian (Nynorsk)"),
    WikiLanguage(code: "nov", name: "Novial"),
    WikiLanguage(code: "oc", name: "Occitan"),
    WikiLanguage(code: "cu", name: "Old Church Slavonic"),
    WikiLanguage(code: "or", name: "Oriya"),
    WikiLanguage(code: "om", name: "Oromo"),
    WikiLanguage(code: "os", name: "Ossetian"),
    WikiLanguage(code: "blk", name: "Pa'O"),
    WikiLanguage(code: "pwn", name: "Paiwan"),
    WikiLanguage(code: "pfl", name: "Palatinate German"),
    WikiLanguage(code: "pi", name: "Pali"),
    WikiLanguage(code: "pag", name: "Pangasinan"),
    WikiLanguage(code: "pap", name: "Papiamentu"),
    WikiLanguage(code: "ps", name: "Pashto"),
    WikiLanguage(code: "pdc", name: "Pennsylvania German"),
    WikiLanguage(code: "fa", name: "Persian"),
    WikiLanguage(code: "pcd", name: "Picard"),
    WikiLanguage(code: "pms", name: "Piedmontese"),
    WikiLanguage(code: "pl", name: "Polish"),
    WikiLanguage(code: "pnt", name: "Pontic"),
    WikiLanguage(code: "pt", name: "Portuguese"),
    WikiLanguage(code: "pa", name: "Punjabi"),
    WikiLanguage(code: "qu", name: "Quechua"),
    WikiLanguage(code: "ksh", name: "Ripuarian"),
    WikiLanguage(code: "rmy", name: "Romani"),
    WikiLanguage(code: "ro", name: "Romanian"),
    WikiLanguage(code: "rm", name: "Romansh"),
    WikiLanguage(code: "ru", name: "Russian"),
    WikiLanguage(code: "rue", name: "Rusyn"),
    WikiLanguage(code: "sah", name: "Sakha"),
    WikiLanguage(code: "szy", name: "Sakizaya"),
    WikiLanguage(code: "sm", name: "Samoan"),
    WikiLanguage(code: "bat-smg", name: "Samogitian"),
    WikiLanguage(code: "sg", name: "Sango"),
    WikiLanguage(code: "sa", name: "Sanskrit"),
    WikiLanguage(code: "sat", name: "Santali"),
    WikiLanguage(code: "skr", name: "Saraiki"),
    WikiLanguage(code: "sc", name: "Sardinian"),
    WikiLanguage(code: "stq", name: "Saterland Frisian"),
    WikiLanguage(code: "sco", name: "Scots"),
    WikiLanguage(code: "gd", name: "Scottish Gaelic"),
    WikiLanguage(code: "trv", name: "Seediq"),
    WikiLanguage(code: "sr", name: "Serbian"),
    WikiLanguage(code: "sh", name: "Serbo-Croatian"),
    WikiLanguage(code: "st", name: "Sesotho"),
    WikiLanguage(code: "shn", name: "Shan"),
    WikiLanguage(code: "sn", name: "Shona"),
    WikiLanguage(code: "ii", name: "Sichuan Yi"),
    WikiLanguage(code: "scn", name: "Sicilian"),
    WikiLanguage(code: "szl", name: "Silesian"),
    WikiLanguage(code: "simple", name: "Simple English"),
    WikiLanguage(code: "sd", name: "Sindhi"),
    WikiLanguage(code: "si", name: "Sinhalese"),
    WikiLanguage(code: "sk", name: "Slovak"),
    WikiLanguage(code: "sl", name: "Slovenian"),
    WikiLanguage(code: "so", name: "Somali"),
    WikiLanguage(code: "ckb", name: "Sorani"),
    WikiLanguage(code: "azb", name: "South Azerbaijani"),
    WikiLanguage(code: "es", name: "Spanish"),
    WikiLanguage(code: "srn", name: "Sranan"),
    WikiLanguage(code: "su", name: "Sundanese"),
    WikiLanguage(code: "sw", name: "Swahili"),
    WikiLanguage(code: "ss", name: "Swati"),
    WikiLanguage(code: "sv", name: "Swedish"),
    WikiLanguage(code: "shi", name: "Tachelhit"),
    WikiLanguage(code: "tl", name: "Tagalog"),
    WikiLanguage(code: "ty", name: "Tahitian"),
    WikiLanguage(code: "tg", name: "Tajik"),
    WikiLanguage(code: "tly", name: "Talysh"),
    WikiLanguage(code: "ta", name: "Tamil"),
    WikiLanguage(code: "roa-tara", name: "Tarantino"),
    WikiLanguage(code: "tt", name: "Tatar"),
    WikiLanguage(code: "te", name: "Telugu"),
    WikiLanguage(code: "tet", name: "Tetum"),
    WikiLanguage(code: "th", name: "Thai"),
    WikiLanguage(code: "bo", name: "Tibetan"),
    WikiLanguage(code: "ti", name: "Tigrinya"),
    WikiLanguage(code: "bbc", name: "Toba Batak"),
    WikiLanguage(code: "tpi", name: "Tok Pisin"),
    WikiLanguage(code: "to", name: "Tongan"),
    WikiLanguage(code: "ts", name: "Tsonga"),
    WikiLanguage(code: "tn", name: "Tswana"),
    WikiLanguage(code: "tcy", name: "Tulu"),
    WikiLanguage(code: "tum", name: "Tumbuka"),
    WikiLanguage(code: "tr", name: "Turkish"),
    WikiLanguage(code: "tk", name: "Turkmen"),
    WikiLanguage(code: "tyv", name: "Tuvan"),
    WikiLanguage(code: "tw", name: "Twi"),
    WikiLanguage(code: "kcg", name: "Tyap"),
    WikiLanguage(code: "udm", name: "Udmurt"),
    WikiLanguage(code: "uk", name: "Ukrainian"),
    WikiLanguage(code: "hsb", name: "Upper Sorbian"),
    WikiLanguage(code: "ur", name: "Urdu"),
    WikiLanguage(code: "ug", name: "Uyghur"),
    WikiLanguage(code: "uz", name: "Uzbek"),
    WikiLanguage(code: "ve", name: "Venda"),
    WikiLanguage(code: "vec", name: "Venetian"),
    WikiLanguage(code: "vep", name: "Vepsian"),
    WikiLanguage(code: "vi", name: "Vietnamese"),
    WikiLanguage(code: "vo", name: "Volapük"),
    WikiLanguage(code: "fiu-vro", name: "Võro"),
    WikiLanguage(code: "wa", name: "Walloon"),
    WikiLanguage(code: "war", name: "Waray-Waray"),
    WikiLanguage(code: "guc", name: "Wayuu"),
    WikiLanguage(code: "cy", name: "Welsh"),
    WikiLanguage(code: "vls", name: "West Flemish"),
    WikiLanguage(code: "fy", name: "West Frisian"),
    WikiLanguage(code: "hyw", name: "Western Armenian"),
    WikiLanguage(code: "pnb", name: "Western Panjabi"),
    WikiLanguage(code: "wo", name: "Wolof"),
    WikiLanguage(code: "wuu", name: "Wu"),
    WikiLanguage(code: "xh", name: "Xhosa"),
    WikiLanguage(code: "yi", name: "Yiddish"),
    WikiLanguage(code: "yo", name: "Yoruba"),
    WikiLanguage(code: "cbk-zam", name: "Zamboanga Chavacano"),
    WikiLanguage(code: "diq", name: "Zazaki"),
    WikiLanguage(code: "zea", name: "Zeelandic"),
    WikiLanguage(code: "za", name: "Zhuang"),
    WikiLanguage(code: "zu", name: "Zulu"),
  ];
}
