export const DEFAULT_BACKEND_HOST = "http://127.0.0.1:8080/";

export const DEFAULT_LANGUAGE_CODE = "en";

export const WIKIPEDIA_LANGUAGES = [
    { "code": "ab", "name": "Abkhazian" },
    { "code": "ace", "name": "Acehnese" },
    { "code": "ady", "name": "Adyghe" },
    { "code": "aa", "name": "Afar" },
    { "code": "af", "name": "Afrikaans" },
    { "code": "ak", "name": "Akan" },
    { "code": "sq", "name": "Albanian" },
    { "code": "als", "name": "Alemannic" },
    { "code": "alt", "name": "Altai" },
    { "code": "am", "name": "Amharic" },
    { "code": "ami", "name": "Amis" },
    { "code": "anp", "name": "Angika" },
    { "code": "ang", "name": "Anglo-Saxon" },
    { "code": "ar", "name": "Arabic" },
    { "code": "an", "name": "Aragonese" },
    { "code": "arc", "name": "Aramaic" },
    { "code": "hy", "name": "Armenian" },
    { "code": "roa-rup", "name": "Aromanian" },
    { "code": "as", "name": "Assamese" },
    { "code": "ast", "name": "Asturian" },
    { "code": "tay", "name": "Atayal" },
    { "code": "atj", "name": "Atikamekw" },
    { "code": "av", "name": "Avar" },
    { "code": "awa", "name": "Awadhi" },
    { "code": "ay", "name": "Aymara" },
    { "code": "az", "name": "Azerbaijani" },
    { "code": "ban", "name": "Balinese" },
    { "code": "bm", "name": "Bambara" },
    { "code": "bjn", "name": "Banjar" },
    { "code": "map-bms", "name": "Banyumasan" },
    { "code": "ba", "name": "Bashkir" },
    { "code": "eu", "name": "Basque" },
    { "code": "bar", "name": "Bavarian" },
    { "code": "be", "name": "Belarusian" },
    { "code": "be-tarask", "name": "Belarusian (Taraškievica)" },
    { "code": "bn", "name": "Bengali" },
    { "code": "bh", "name": "Bihari" },
    { "code": "bpy", "name": "Bishnupriya Manipuri" },
    { "code": "bi", "name": "Bislama" },
    { "code": "bs", "name": "Bosnian" },
    { "code": "br", "name": "Breton" },
    { "code": "bug", "name": "Buginese" },
    { "code": "bg", "name": "Bulgarian" },
    { "code": "my", "name": "Burmese" },
    { "code": "bxr", "name": "Buryat (Russia)" },
    { "code": "zh-yue", "name": "Cantonese" },
    { "code": "ca", "name": "Catalan" },
    { "code": "ceb", "name": "Cebuano" },
    { "code": "bcl", "name": "Central Bicolano" },
    { "code": "ch", "name": "Chamorro" },
    { "code": "ce", "name": "Chechen" },
    { "code": "chr", "name": "Cherokee" },
    { "code": "chy", "name": "Cheyenne" },
    { "code": "ny", "name": "Chichewa" },
    { "code": "zh", "name": "Chinese" },
    { "code": "cho", "name": "Choctaw" },
    { "code": "cv", "name": "Chuvash" },
    { "code": "zh-classical", "name": "Classical Chinese" },
    { "code": "kw", "name": "Cornish" },
    { "code": "co", "name": "Corsican" },
    { "code": "cr", "name": "Cree" },
    { "code": "crh", "name": "Crimean Tatar" },
    { "code": "hr", "name": "Croatian" },
    { "code": "cs", "name": "Czech" },
    { "code": "dga", "name": "Dagaare" },
    { "code": "dag", "name": "Dagbani" },
    { "code": "da", "name": "Danish" },
    { "code": "din", "name": "Dinka" },
    { "code": "dv", "name": "Divehi" },
    { "code": "dty", "name": "Doteli" },
    { "code": "nl", "name": "Dutch" },
    { "code": "nds-nl", "name": "Dutch Low Saxon" },
    { "code": "dz", "name": "Dzongkha" },
    { "code": "arz", "name": "Egyptian Arabic" },
    { "code": "eml", "name": "Emilian-Romagnol" },
    { "code": "en", "name": "English" },
    { "code": "myv", "name": "Erzya" },
    { "code": "eo", "name": "Esperanto" },
    { "code": "et", "name": "Estonian" },
    { "code": "ee", "name": "Ewe" },
    { "code": "ext", "name": "Extremaduran" },
    { "code": "fat", "name": "Fante" },
    { "code": "fo", "name": "Faroese" },
    { "code": "hif", "name": "Fiji Hindi" },
    { "code": "fj", "name": "Fijian" },
    { "code": "fi", "name": "Finnish" },
    { "code": "fon", "name": "Fon" },
    { "code": "frp", "name": "Franco-Provençal/Arpitan" },
    { "code": "fr", "name": "French" },
    { "code": "fur", "name": "Friulian" },
    { "code": "ff", "name": "Fula" },
    { "code": "gag", "name": "Gagauz" },
    { "code": "gl", "name": "Galician" },
    { "code": "gan", "name": "Gan" },
    { "code": "ka", "name": "Georgian" },
    { "code": "de", "name": "German" },
    { "code": "gpe", "name": "Ghanaian Pidgin" },
    { "code": "glk", "name": "Gilaki" },
    { "code": "gom", "name": "Goan Konkani" },
    { "code": "gor", "name": "Gorontalo" },
    { "code": "got", "name": "Gothic" },
    { "code": "el", "name": "Greek" },
    { "code": "kl", "name": "Greenlandic" },
    { "code": "gn", "name": "Guarani" },
    { "code": "gcr", "name": "Guianan Creole" },
    { "code": "gu", "name": "Gujarati" },
    { "code": "guw", "name": "Gun" },
    { "code": "gur", "name": "Gurenɛ" },
    { "code": "ht", "name": "Haitian" },
    { "code": "hak", "name": "Hakka" },
    { "code": "ha", "name": "Hausa" },
    { "code": "haw", "name": "Hawaiian" },
    { "code": "he", "name": "Hebrew" },
    { "code": "hz", "name": "Herero" },
    { "code": "mrj", "name": "Hill Mari" },
    { "code": "hi", "name": "Hindi" },
    { "code": "ho", "name": "Hiri Motu" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "is", "name": "Icelandic" },
    { "code": "io", "name": "Ido" },
    { "code": "ig", "name": "Igbo" },
    { "code": "ilo", "name": "Ilokano" },
    { "code": "smn", "name": "Inari Sami" },
    { "code": "id", "name": "Indonesian" },
    { "code": "inh", "name": "Ingush" },
    { "code": "ia", "name": "Interlingua" },
    { "code": "ie", "name": "Interlingue" },
    { "code": "iu", "name": "Inuktitut" },
    { "code": "ik", "name": "Inupiak" },
    { "code": "ga", "name": "Irish" },
    { "code": "it", "name": "Italian" },
    { "code": "jam", "name": "Jamaican" },
    { "code": "ja", "name": "Japanese" },
    { "code": "jv", "name": "Javanese" },
    { "code": "kbd", "name": "Kabardian Circassian" },
    { "code": "kbp", "name": "Kabiye" },
    { "code": "kab", "name": "Kabyle" },
    { "code": "xal", "name": "Kalmyk" },
    { "code": "kn", "name": "Kannada" },
    { "code": "kr", "name": "Kanuri" },
    { "code": "pam", "name": "Kapampangan" },
    { "code": "krc", "name": "Karachay-Balkar" },
    { "code": "kaa", "name": "Karakalpak" },
    { "code": "ks", "name": "Kashmiri" },
    { "code": "csb", "name": "Kashubian" },
    { "code": "kk", "name": "Kazakh" },
    { "code": "km", "name": "Khmer" },
    { "code": "ki", "name": "Kikuyu" },
    { "code": "rw", "name": "Kinyarwanda" },
    { "code": "ky", "name": "Kirghiz" },
    { "code": "rn", "name": "Kirundi" },
    { "code": "kv", "name": "Komi" },
    { "code": "koi", "name": "Komi-Permyak" },
    { "code": "kg", "name": "Kongo" },
    { "code": "ko", "name": "Korean" },
    { "code": "avk", "name": "Kotava" },
    { "code": "kj", "name": "Kuanyama" },
    { "code": "ku", "name": "Kurdish" },
    { "code": "lld", "name": "Ladin" },
    { "code": "lad", "name": "Ladino" },
    { "code": "lbe", "name": "Lak" },
    { "code": "lo", "name": "Lao" },
    { "code": "ltg", "name": "Latgalian" },
    { "code": "la", "name": "Latin" },
    { "code": "lv", "name": "Latvian" },
    { "code": "lez", "name": "Lezgian" },
    { "code": "lij", "name": "Ligurian" },
    { "code": "li", "name": "Limburgish" },
    { "code": "ln", "name": "Lingala" },
    { "code": "lfn", "name": "Lingua Franca Nova 2" },
    { "code": "lt", "name": "Lithuanian" },
    { "code": "olo", "name": "Livvi-Karelian" },
    { "code": "jbo", "name": "Lojban" },
    { "code": "lmo", "name": "Lombard" },
    { "code": "nds", "name": "Low Saxon" },
    { "code": "dsb", "name": "Lower Sorbian" },
    { "code": "lg", "name": "Luganda" },
    { "code": "lb", "name": "Luxembourgish" },
    { "code": "mk", "name": "Macedonian" },
    { "code": "mad", "name": "Madurese" },
    { "code": "mai", "name": "Maithili" },
    { "code": "mg", "name": "Malagasy" },
    { "code": "ms", "name": "Malay" },
    { "code": "ml", "name": "Malayalam" },
    { "code": "mt", "name": "Maltese" },
    { "code": "gv", "name": "Manx" },
    { "code": "mi", "name": "Maori" },
    { "code": "mr", "name": "Marathi" },
    { "code": "mh", "name": "Marshallese" },
    { "code": "mzn", "name": "Mazandarani" },
    { "code": "mhr", "name": "Meadow Mari" },
    { "code": "mni", "name": "Meitei" },
    { "code": "cdo", "name": "Min Dong" },
    { "code": "zh-min-nan", "name": "Min Nan" },
    { "code": "min", "name": "Minangkabau" },
    { "code": "xmf", "name": "Mingrelian" },
    { "code": "mwl", "name": "Mirandese" },
    { "code": "mdf", "name": "Moksha" },
    { "code": "mnw", "name": "Mon" },
    { "code": "mn", "name": "Mongolian" },
    { "code": "zgh", "name": "Moroccan Amazigh" },
    { "code": "ary", "name": "Moroccan Arabic" },
    { "code": "mus", "name": "Muscogee" },
    { "code": "nqo", "name": "N'Ko" },
    { "code": "nah", "name": "Nahuatl" },
    { "code": "na", "name": "Nauruan" },
    { "code": "nv", "name": "Navajo" },
    { "code": "ng", "name": "Ndonga" },
    { "code": "nap", "name": "Neapolitan" },
    { "code": "ne", "name": "Nepali" },
    { "code": "new", "name": "Newar / Nepal Bhasa" },
    { "code": "nia", "name": "Nias" },
    { "code": "pcm", "name": "Nigerian Pidgin" },
    { "code": "pih", "name": "Norfolk" },
    { "code": "nrm", "name": "Norman" },
    { "code": "frr", "name": "North Frisian" },
    { "code": "lrc", "name": "Northern Luri" },
    { "code": "se", "name": "Northern Sami" },
    { "code": "nso", "name": "Northern Sotho" },
    { "code": "no", "name": "Norwegian (Bokmål)" },
    { "code": "nn", "name": "Norwegian (Nynorsk)" },
    { "code": "nov", "name": "Novial" },
    { "code": "oc", "name": "Occitan" },
    { "code": "cu", "name": "Old Church Slavonic" },
    { "code": "or", "name": "Oriya" },
    { "code": "om", "name": "Oromo" },
    { "code": "os", "name": "Ossetian" },
    { "code": "blk", "name": "Pa'O" },
    { "code": "pwn", "name": "Paiwan" },
    { "code": "pfl", "name": "Palatinate German" },
    { "code": "pi", "name": "Pali" },
    { "code": "pag", "name": "Pangasinan" },
    { "code": "pap", "name": "Papiamentu" },
    { "code": "ps", "name": "Pashto" },
    { "code": "pdc", "name": "Pennsylvania German" },
    { "code": "fa", "name": "Persian" },
    { "code": "pcd", "name": "Picard" },
    { "code": "pms", "name": "Piedmontese" },
    { "code": "pl", "name": "Polish" },
    { "code": "pnt", "name": "Pontic" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "pa", "name": "Punjabi" },
    { "code": "qu", "name": "Quechua" },
    { "code": "ksh", "name": "Ripuarian" },
    { "code": "rmy", "name": "Romani" },
    { "code": "ro", "name": "Romanian" },
    { "code": "rm", "name": "Romansh" },
    { "code": "ru", "name": "Russian" },
    { "code": "rue", "name": "Rusyn" },
    { "code": "sah", "name": "Sakha" },
    { "code": "szy", "name": "Sakizaya" },
    { "code": "sm", "name": "Samoan" },
    { "code": "bat-smg", "name": "Samogitian" },
    { "code": "sg", "name": "Sango" },
    { "code": "sa", "name": "Sanskrit" },
    { "code": "sat", "name": "Santali" },
    { "code": "skr", "name": "Saraiki" },
    { "code": "sc", "name": "Sardinian" },
    { "code": "stq", "name": "Saterland Frisian" },
    { "code": "sco", "name": "Scots" },
    { "code": "gd", "name": "Scottish Gaelic" },
    { "code": "trv", "name": "Seediq" },
    { "code": "sr", "name": "Serbian" },
    { "code": "sh", "name": "Serbo-Croatian" },
    { "code": "st", "name": "Sesotho" },
    { "code": "shn", "name": "Shan" },
    { "code": "sn", "name": "Shona" },
    { "code": "ii", "name": "Sichuan Yi" },
    { "code": "scn", "name": "Sicilian" },
    { "code": "szl", "name": "Silesian" },
    { "code": "simple", "name": "Simple English" },
    { "code": "sd", "name": "Sindhi" },
    { "code": "si", "name": "Sinhalese" },
    { "code": "sk", "name": "Slovak" },
    { "code": "sl", "name": "Slovenian" },
    { "code": "so", "name": "Somali" },
    { "code": "ckb", "name": "Sorani" },
    { "code": "azb", "name": "South Azerbaijani" },
    { "code": "es", "name": "Spanish" },
    { "code": "srn", "name": "Sranan" },
    { "code": "su", "name": "Sundanese" },
    { "code": "sw", "name": "Swahili" },
    { "code": "ss", "name": "Swati" },
    { "code": "sv", "name": "Swedish" },
    { "code": "shi", "name": "Tachelhit" },
    { "code": "tl", "name": "Tagalog" },
    { "code": "ty", "name": "Tahitian" },
    { "code": "tg", "name": "Tajik" },
    { "code": "tly", "name": "Talysh" },
    { "code": "ta", "name": "Tamil" },
    { "code": "roa-tara", "name": "Tarantino" },
    { "code": "tt", "name": "Tatar" },
    { "code": "te", "name": "Telugu" },
    { "code": "tet", "name": "Tetum" },
    { "code": "th", "name": "Thai" },
    { "code": "bo", "name": "Tibetan" },
    { "code": "ti", "name": "Tigrinya" },
    { "code": "bbc", "name": "Toba Batak" },
    { "code": "tpi", "name": "Tok Pisin" },
    { "code": "to", "name": "Tongan" },
    { "code": "ts", "name": "Tsonga" },
    { "code": "tn", "name": "Tswana" },
    { "code": "tcy", "name": "Tulu" },
    { "code": "tum", "name": "Tumbuka" },
    { "code": "tr", "name": "Turkish" },
    { "code": "tk", "name": "Turkmen" },
    { "code": "tyv", "name": "Tuvan" },
    { "code": "tw", "name": "Twi" },
    { "code": "kcg", "name": "Tyap" },
    { "code": "udm", "name": "Udmurt" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "hsb", "name": "Upper Sorbian" },
    { "code": "ur", "name": "Urdu" },
    { "code": "ug", "name": "Uyghur" },
    { "code": "uz", "name": "Uzbek" },
    { "code": "ve", "name": "Venda" },
    { "code": "vec", "name": "Venetian" },
    { "code": "vep", "name": "Vepsian" },
    { "code": "vi", "name": "Vietnamese" },
    { "code": "vo", "name": "Volapük" },
    { "code": "fiu-vro", "name": "Võro" },
    { "code": "wa", "name": "Walloon" },
    { "code": "war", "name": "Waray-Waray" },
    { "code": "guc", "name": "Wayuu" },
    { "code": "cy", "name": "Welsh" },
    { "code": "vls", "name": "West Flemish" },
    { "code": "fy", "name": "West Frisian" },
    { "code": "hyw", "name": "Western Armenian" },
    { "code": "pnb", "name": "Western Panjabi" },
    { "code": "wo", "name": "Wolof" },
    { "code": "wuu", "name": "Wu" },
    { "code": "xh", "name": "Xhosa" },
    { "code": "yi", "name": "Yiddish" },
    { "code": "yo", "name": "Yoruba" },
    { "code": "cbk-zam", "name": "Zamboanga Chavacano" },
    { "code": "diq", "name": "Zazaki" },
    { "code": "zea", "name": "Zeelandic" },
    { "code": "za", "name": "Zhuang" },
    { "code": "zu", "name": "Zulu" },
];
